# POSTGRESQL DOCKER

# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: projet_name_db
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: projet_name_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


# MYSQL DOCKER
networks:
  projet_name:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: projet_name_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_name_db
    ports:
      - "3306:3306"
    networks:
      - projet_name
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
